# Generated by Django 4.1.1 on 2022-09-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=50)),
                ('county_fips', models.IntegerField()),
                ('state', models.CharField(max_length=50)),
                ('county_population', models.IntegerField()),
                ('health_service_area_number', models.IntegerField()),
                ('health_service_area', models.TextField()),
                ('health_service_area_population', models.IntegerField(blank=True, null=True)),
                ('covid_inpatient_bed_utilization', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('covid_hospital_admissions_per_100k', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('covid_cases_per_100k', models.DecimalField(decimal_places=2, max_digits=7)),
                ('covid19_community_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=6, null=True)),
                ('date_updated', models.DateField()),
            ],
        ),
    ]
